apiVersion: v1
kind: Secret
metadata:
  name: shopeasy-secrets
  namespace: development
type: Opaque
stringData:
  DB_USER: shopeasy_davidlekkzy
  DB_PASSWORD: my_strong_postgres_password
  REDIS_PASSWORD: my_strong_redis_password